os:
  - linux
# this is build on container-based ci
# if sudo will not
#sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
cache:
  yarn: true
  directories:
    - node_modules
#before_install:
#    - apt-get update &&  apt-get install yarn
install:
  - rm -rf package.json
  - mv package.complie.json package.json
  - npm install
#  - yarn install
before_script:
  - echo "begin"
  - git config --global user.name "tianzx"
  - git config --global user.email "tianzx@aliyun.com"
script:
  # 生成静态文件
  - npm run build
after_script:
  # 将生成的静态文件，初始化为 git 仓库
  - cd  dist
  - git init
  - git config user.name "tianzx"
  - git config user.email "tianzx@aliyun.com"
  - git add --all
  - git commit -m "push from the travis server"
  # 推送到 ui-dist 分支
  - git push --force  "https://${GH_Token}@${GH_REF}" master
after_success:
  - echo "success "
env:
  global:
    - GH_REF: github.com/tianzx/ui-dist.git
#    - secure: "jYZ9BEIr4tZ4EaWYhDjBX+hkrFEPE2epeRVOvs/zM2HY5S5FhlABzdVrGNwIywIaf7Sxp4HSPBsUJwfIueM/GVaTFLdTJxbzErkZMrwKURSlMib5/rcO/oQDQTK1bmnQJBrT0Cc6tRgcql/2y+19E++w0bXo6kvqtq7fX68rxmBpls1Kdjut/sGYDmQAONI+iy8NcT1ndgQN3FxiLnm3dN6ktKtuPgBsG50GuDF7Sq6tNz45P8nQ9XPQgXFXTrk3mMTD6p220XHXrkymOqvkoPGlHT2khkGqQYqR7MGcU7qlm3Eu5Fp1wpq8A0nKjRTpb2JYk0fhxyobuy0PVuj4l2OXd88Cr9VoEpQ6d/DR+xlO2zxIBKsdkgo4R0k2ZrBI5q5cBVq5VIVsT3M1bmUmcBqo47M/adKUNaqQLRcjQzAjyiGaiqzPxKznZ2hPq33KKyACQOlZBWQufImgOgO+HKi6aKBGjtH4xJ/WkQcgmBZDquto+1QUx7i2rZFLDesLVTTbGgit5XXuoZKY4K/yiU2Jq3zstSELHPiaoFf2IFjyTwz+/2gbIuK+S5uOlkELdanMUEDNbpNkoEMXMnFFyGIMFEh17jj5vHTtn0b6cs5EnWDIC/i3u7sQzbWnEXAn1igt2+PcDWFPZmrfPD5wjfA8HpNPN4zehikjmTA5Xqs="
