language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - echo "begin"
  - git config --global user.name "tianzx"
  - git config --global user.email "tianzx@aliyun.com"
script:
  # 生成静态文件
  - npm run build
after_script:
  # 将生成的静态文件，初始化为 git 仓库
  - cd  dist
  - git init
  - git config user.name "tianzx"
  - git config user.email "tianzx@aliyun.com"
  - git add --all
  - git commit -m "push from the travis server"
  # 推送到 ui-dist 分支
  - git push --force  "https://${GH_Token}@${GH_REF}" master
after_success:
  - echo "success"
env:
  global:
    - GH_REF: github.com/tianzx/ui-dist.git
    - secure: "BLVgVNCqG1FGsShweITQnxNPnRJDU9igz5+qy1OdjJ0+tRqSFX+QUNSELEu+Dxy2kglhBWnz90LEIF5kTDd1A/6MwuIHGYjnvoMS252+UiL56g0Wb2F2N8juRbw8hog+dGMRJ0Dp2veqEZS2VecRmQ1PiyNtOqV8k2kUK/ImewBlNDRwEi0Amb3xt5ZZZUMY1Hz3aEOdP0K1IWmm95wOvNM18rsmpWLpQPFYZkMdJY/hfz5vAG5TaiUpvXUmIb/eodbjggN1wRBxrkBMGp2TXdDQu60HUSwVjmDabnC5f8Gtmsd6hkh5XGB/R9M66ndMBX/BT5at1DJerBM66ywxoadgLqRkWJjLgZVARtaWEVYh8llvIG3BgFCoOXHLJfmdVF+AguxreYiLYzwWE44vsoSB2Ctsv9zPotWMl9leuPcD+WZzEAzeXJsGyqgSogBtojPS1GwT78zq1PgyciaFYVbjCVja7sjG6Ioa0AMp1vrQ2PfisCgYV4lZEq+XwvY2g7L1LTpGN1viT6T6nxyMdVDUbUZ+fUChzOEebJhbXr42dtspnT5ZAwfiZo/3pLQ9BRvSxDpsKbXxFb7vgiA0zu+N2qF6LB1/igZ8lM395qbaP6pbP/sYlk7wZGevfR5ur473bT6xh7NH1g1oZVrcr7dC8hTzNcbQnKt/k2sjQac="
